spring.application.name=05_microservicio_alumnos
#configuracion de la base de datos personasbd de tipo h2
spring.datasource.url=jdbc:h2:mem:alumnosbd
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
#configuracion de jpa para crear las tablas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#configuracion de h2 console para acceder a la base de datos desde el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
#configuracion de propiedades de nombrado de campos de hibernate para que coincidan con los nombres de las columnas de la base de datos
spring.jpa.properties.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategy
spring.jpa.properties.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
